# reference at https://alacritty.org/config-alacritty.html

[general]
import = ["~/.config/alacritty/e-ink-dark.toml"]

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 2, y = 2 }
dynamic_padding = false
decorations = "full"
opacity = 1.0
blur = false

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 11.0

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = []
